// Generated by CoffeeScript 1.4.0
var facilities, findBeds, findFacilities, findRooms, hideResidentControls, initialize, postNewPatient, showResidentControls;

facilities = {};

$(document).ready(function() {
	$.getJSON('count',function(data) {
	    $('#inputPatientID').val(data);
	  });
	
  return initialize();
});

initialize = function() {
  $('#residentControls').hide();
  $('#discharged').click(hideResidentControls);
  $('#outpatient').click(hideResidentControls);
  $('#residentPatient').click(showResidentControls);
  $('#inputAdmittingPhysician').val(currentPhysician);
  $('#facility').change(function() {
    return findRooms();
  });
  $('#room').change(function() {
    return findBeds();
  });
  return findFacilities();
};

hideResidentControls = function() {
  $('#residentControls').hide();
  $('#room').html('');
  $('#room').append('<option value="0">---</option>');
  $('#bed').html('');
  return $('#bed').append('<option value="0">---</option>');
};

showResidentControls = function() {
  $('#residentControls').show();
  return $('#facility').val(0);
};

findFacilities = function() {
  var key, value;
  for (key in residency) {
    value = residency[key];
    facilities[value.facilityNo] = value.facilityName;
  }
  for (key in facilities) {
    value = facilities[key];
    $('#facility').append('<option value="' + key + '">' + value + '</option>');
  }
  return findRooms();
};

findRooms = function() {
  var key, selectedOption, tempRooms, value;
  $('#room').html('');
  tempRooms = {};
  selectedOption = parseInt($('#facility option:selected').attr('value'));
  for (key in residency) {
    value = residency[key];
    if (value.facilityNo === selectedOption) {
      tempRooms[value.roomNo] = value.roomNo;
    }
  }
  for (key in tempRooms) {
    value = tempRooms[key];
    $('#room').append('<option value="' + key + '">' + value + '</option>');
  }
  return findBeds();
};

findBeds = function() {
  var key, selectedOption, tempBeds, value, _results;
  $('#bed').html('');
  tempBeds = {};
  selectedOption = parseInt($('#room option:selected').attr('value'));
  for (key in residency) {
    value = residency[key];
    if (value.roomNo === selectedOption) {
      tempBeds[value.bedNo] = value.bedNo;
    }
  }
  _results = [];
  for (key in tempBeds) {
    value = tempBeds[key];
    _results.push($('#bed').append('<option value="' + key + '">' + value + '</option>'));
  }
  return _results;
};

postNewPatient = function() {
  var address, admittingPhysician, bedNo, city, fName, facilityNo, lName, newPatient, patientID, phone, roomNo, state, type, zip;
  newPatient = {};
  fName = $('#inputFName').val();
  lName = $('#inputLName').val();
  patientID = $('#inputPatientID').val();
  admittingPhysician = $('#inputAdmittingPhysician').val();
  address = $('#inputAddress').val();
  city = $('#inputCity').val();
  state = $('#inputState').val();
  zip = $('#inputZipcode').val();
  phone = $('#inputPhone').val();
  type = null;
  facilityNo = 11;
  roomNo = 1;
  bedNo = 1;
  if ($('#discharged').attr('checked') === 'checked') {
    type = 'Discharged';
  } else if ($('#residentPatient').attr('checked') === 'checked') {
    type = 'Resident';
  } else {
    type = 'Outpatient';
  }
  if (type === 'Resident') {
    facilityNo = $('#facility').val();
    roomNo = $('#room').val();
    bedNo = $('#bed').val();
  }
  newPatient.fName = fName;
  newPatient.lName = lName;
  newPatient.patientID = patientID;
  newPatient.admittingPhysician = admittingPhysician;
  newPatient.address = address;
  newPatient.city = city;
  newPatient.state = state;
  newPatient.zip = zip;
  newPatient.phone = phone;
  newPatient.type = type;
  newPatient.facilityNo = facilityNo;
  newPatient.roomNo = roomNo;
  newPatient.bedNo = bedNo;

  $.post("create", newPatient);

  
  return alert('patient added');
};
