// Generated by CoffeeScript 1.4.0
var currentPatientKey, displayInfo, facilities, filterTable, findBeds, findFacilities, findRooms, findText, hideResidentControls, iNumber, iString, initialize, input, patients, populateTable, postUpdate, showResidentControls;

input = null;

iNumber = null;

iString = '';

currentPatientKey = null;

facilities = {};

patients = {};

storedInfo = {};

diagnoseURL = null;

$(document).ready(function() {
  return $.getJSON('patientId/',function(data) {
    patients = data;
    return initialize();
  });
});

initialize = function() {
  $('#searchBox').bind('propertychange input paste', findText);
  $('#residentControls').hide();
  $('#discharged').click(hideResidentControls);
  $('#outpatient').click(hideResidentControls);
  $('#residentPatient').click(showResidentControls);
  populateTable();
  $('#facility').change(function() {
    return findRooms();
  });
  $('#room').change(function() {
    return findBeds();
  });
  return findFacilities();
};

populateTable = function() {
  var dateAdmitted, fname, key, lname, value, _results;
  _results = [];
  $("#dataTableBody tr").remove();
  for (key in patients) {
    value = patients[key];
    fname = value.fname;
    lname = value.lname;
    patientId = value.patientId;
    dateAdmitted = value.dateAdmitted;
    _results.push($('#dataTableBody').append('\
			<tr id="' + patientId + '" onclick=displayInfo(' + patientId + ',' + key +')>\
				<td>' + fname + '</td>\
				<td>' + lname + '</td>\
				<td>' + dateAdmitted + '</td>\
				<td>' + patientId + '</td>\
			</tr>'));
  }
  return _results;
};




hideResidentControls = function() {
  $('#residentControls').hide();
  $('#room').html('');
  $('#room').append('<option value="0">---</option>');
  $('#bed').html('');
  return $('#bed').append('<option value="0">---</option>');
};

showResidentControls = function() {
  $('#residentControls').show();
  return $('#facility').val(0);
};

findFacilities = function() {
  var key, value;
  console.log('findFacilities');
  for (key in residency) {
    value = residency[key];
    facilities[value.facilityNo] = value.facilityName;
  }
  for (key in facilities) {
    value = facilities[key];
    $('#facility').append('<option value="' + key + '">' + value + '</option>');
  }
  return findRooms();
};

findRooms = function() {
  var key, selectedOption, tempRooms, value;
  console.log('findRooms');
  $('#room').html('');
  tempRooms = {};
  selectedOption = parseInt($('#facility option:selected').attr('value'));
  for (key in residency) {
    value = residency[key];
    if (value.facilityNo === selectedOption) {
      tempRooms[value.roomNo] = value.roomNo;
    }
  }
  for (key in tempRooms) {
    value = tempRooms[key];
    $('#room').append('<option value="' + key + '">' + value + '</option>');
  }
  return findBeds();
};

findBeds = function() {
  var key, selectedOption, tempBeds, value, _results;
  console.log('findBeds');
  $('#bed').html('');
  tempBeds = {};
  selectedOption = parseInt($('#room option:selected').attr('value'));
  for (key in residency) {
    value = residency[key];
    if (value.roomNo === selectedOption) {
      tempBeds[value.bedNo] = value.bedNo;
    }
  }
  _results = [];
  for (key in tempBeds) {
    value = tempBeds[key];
    _results.push($('#bed').append('<option value="' + key + '">' + value + '</option>'));
  }
  return _results;
};

findText = function() {
  input = $('#searchBox').val();
  iNumber = input.replace(/[a-zA-z]/g, '').toLowerCase();
  iString = input.replace(/[0-9]/g, '').toLowerCase();
  return filterTable();
};

displayInfo = function(patientID, key) {
  var patient;
  $('#deleteButton').attr('disabled', false);
  $('#diagnose').attr("action", "../diagnose/?patientId="+patientID); 
  currentPatientKey = patientID;
  $('tr').removeClass('highlight');
  $('#' + patientID).addClass('highlight');
  patient = patients[key];
  $('#name').val(patient.fname + ' ' + patient.lname);
  $('#phone').val(patient.phone);
  $('#address').val(patient.address);
  $('#city').val(patient.city);
  $('#zip').val(patient.zip);
  $('#state').val(patient.state);
  $('#patientID').val(patientID);
  $('#referringPhysician').val(patient.referringPhysician);
  if (patient.patientType === 'Outpatient') {
    $('#outpatient').prop('checked', true);
    return hideResidentControls();
  } else if (patient.patientType === 'Discharged') {
    $('#discharged').prop('checked', true);
    return hideResidentControls();
  } else {
    $('#residentPatient').prop('checked', true);
    $('#residentControls').show();
    $('#facility').val(patient.facilityNo);
    findRooms();
    $('#room').val(patient.roomNo);
    findBeds();
    return $('bed').val(patient.bedNo);
  }
};

filterTable = function() {
  var fname, key, lname, regexNumber, regexString, value, _results;
  if (input === null || input === '') {
    return $('#dataTableBody tr').show();
  } else {
    if (iString === null || iString === '') {
      regexString = null;
    } else {
      regexString = new RegExp(iString, 'g');
    }
    if (iNumber === null || iNumber === '') {
      regexNumber = null;
    } else {
      regexNumber = new RegExp(iNumber, 'g');
    }
    _results = [];
    for (key in patients) {
      value = patients[key];
      fname = (fname == null)? null : value.fname.toLowerCase();
      lname = (lname == null)? null :value.lname.toLowerCase();
      console.log('--- ---');
      if (regexNumber !== null && value.patientId.toString().match(regexNumber)) {
        _results.push($('#' + value.patientId).show());
      } else if (regexString !== null && (fname.match(regexString) || lname.match(regexString))) {
        _results.push($('#' + value.patientId).show());
      } else {
        _results.push($('#' + value.patientId).hide());
      }
    }
    return _results;
  }
};

deletePatient = function() {
	  $.getJSON("delete/"+currentPatientKey,function(data){	  
			    patients = data;
			    initialize();
	  });
	  
	 
	};

postUpdate = function() {
  var pAddress, pBedNo, pCity, pFacility, pFacilityNo, pPhone, pRoomNo, pState, pType, pZip, patientUpdate;
  patientUpdate = {};
  pPhone = $('#phone').val();
  pAddress = $('#address').val();
  pCity = $('#city').val();
  pState = $('#state').val();
  pZip = $('zip').val();
  pType = null;
  pFacilityNo = 0;
  pRoomNo = 0;
  pBedNo = 0;
  if ($('#discharged').attr('checked') === 'checked') {
    pType = 'Discharged';
  } else if ($('#residentPatient').attr('checked') === 'checked') {
    pType = 'Resident';
  } else {
    pType = 'Outpatient';
  }
  if (pType === 'Resident') {
	pFacilityNo = $('#facility').val();
    pRoomNo = $('#room').val();
    pBedNo = $('#bed').val();
  }
  patientUpdate.patientNo = currentPatientKey;
  patientUpdate.phone = pPhone;
  patientUpdate.address = pAddress;
  patientUpdate.city = pCity;
  patientUpdate.state = pState;
  patientUpdate.zip = pZip;
  patientUpdate.pType = pType;
  patientUpdate.pFacilityNo = pFacilityNo;
  patientUpdate.pRoomNo = pRoomNo;
  patientUpdate.pBedNo = pBedNo;
  $.post("update/"+patientUpdate.patientNo, patientUpdate);
  $.getJSON('patientId/',function(data) {
    patients = data;
    return initialize();
  });
  storedInfo.patientID = currentPatientKey;
  $('#'.currentPatientKey).click();
  return alert('patient updated');
};
